name: Python CI/CD with Allure and GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Quan trọng để push được lên gh-pages

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Kill Chrome processes
      run: |
        pkill chrome || true
        pkill chromedriver || true

    - name: Run tests with Allure result generation
      run: |
        pytest --alluredir=allure-results

    - name: Install Allure Commandline
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -qO- https://github.com/allure-framework/allure2/releases/download/2.22.1/allure-2.22.1.zip > allure.zip
        unzip -q allure.zip -d $HOME/.allure
        echo "$HOME/.allure/allure-2.22.1/bin" >> $GITHUB_PATH

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Add .nojekyll to report
      run: |
        touch allure-report/.nojekyll

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages
