name: Python CI/CD with Allure and GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Quan trọng để push được lên gh-pages

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Kill Chrome processes
      run: |
        pkill chrome || true
        pkill chromedriver || true

    - name: Run tests with Allure result generation
      run: |
        pytest --alluredir=allure-results

    - name: Install Allure Commandline
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -qO- https://github.com/allure-framework/allure2/releases/download/2.22.1/allure-2.22.1.zip > allure.zip
        unzip -q allure.zip -d $HOME/.allure
        echo "$HOME/.allure/allure-2.22.1/bin" >> $GITHUB_PATH

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Deploy Allure report to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Checkout or create gh-pages branch
        if git show-ref --verify --quiet refs/heads/gh-pages; then
          git checkout gh-pages
        else
          git checkout --orphan gh-pages
        fi

        # Clear old files
        git rm -rf . || true

        # Copy new report files
        cp -r ../allure-report/* .

        # Commit and push
        git add .
        git commit -m "Update Allure report from CI build $GITHUB_RUN_ID" || echo "No changes to commit"
        git push origin gh-pages --force
